#!/bin/bash
#
# Autogeenerate Script
#
input=$1

echo Input $input
Rscript -e "library(knitr); library(rmarkdown) ; knit(\"${input}.Rmd\",\"${input}.md\"); render(\"${input}.md\") ; browseURL(\"${input}.html\") "
#pandoc -r markdown -w html -o out.html test.md
#pandoc -s -t s5 --mathjax ${input}.md -o out.html
#wkhtmltopdf out.html out.pdf
